name: Automatic Infra-scripts Release

on:
  push:
    branches:
      - main

jobs:
  github-release:
    uses: Aventus-Network-Services/Infra-scripts/.github/workflows/automatic-releases.yaml@v4.0.0
    with:
      default_bump: minor
    secrets: inherit