name: Automatic Release

on:
  workflow_call:
    inputs:
      default_bump:
        required: false
        type: string
        default: none
    secrets:
      envPat:
        required: true

jobs:
  tag:
    name: Bump version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Initial commit')"

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ inputs.token }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.envPat }}
          WITH_V: true
          DEFAULT_BUMP: ${{ inputs.default_bump }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
          generate_release_notes: true