name: Docker Build

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: ubuntu-20.04
      config_creds:
        required: false
        type: boolean
        default: true
      aws_region:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      git_context:
        required: false
        type: string
        default: .
      ecr_repository_name:
        required: true
        type: string
      default_branch:
        required: false
        type: string
        default: master
      create_pr_dtag:
        required: false
        type: boolean
        default: false
      create_latest_dtag:
        required: false
        type: boolean
        default: false
      create_commit_hash_dtag:
        required: false
        type: boolean
        default: false
      create_git_ref_dtag:
        required: false
        type: boolean
        default: false
      docker_args_list:
        required: false
        type: string
      dockerfile:
        required: false
        type: string
      working_directory:
        required: false
        type: string
    secrets:
      aws_access_key:
        required: false
      aws_secret_key:
        required: false

env:
  ECR_REPO: ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}

jobs:
  docker-build:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        if: ${{ inputs.config_creds }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to the AWS registry
        run: |
          aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com

      - name: Create tag for PR
        if: ${{ inputs.create_pr_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create latest tag
        if: ${{ inputs.create_latest_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:latest" >> $GITHUB_ENV

      - name: Create commit hash tag
        if: ${{ inputs.create_commit_hash_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create docker tag for ${GITHUB_REF#refs/*/}
        if: ${{ inputs.create_git_ref_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set working directory
        if: ${{ inputs.working_directory != '' }}
        run: |
          cd ${{ inputs.working_directory }}

      - name: Build and push
        if: ${{ env.DOCKER_TAG != '' }}
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ inputs.git_context }}"
          build-contexts: ${{ inputs.working_directory }}
          push: true
          tags: ${{ env.DOCKER_TAG }}
          provenance: false
          build-args: ${{ inputs.docker_args_list }}
          file: ${{ inputs.dockerfile }}

      - name: Fail if no DOCKER_TAGS are specified
        if: ${{ env.DOCKER_TAG == '' }}
        run: |
          echo "NO DOCKER TAGS SPECIFIED. ACTION FAILED. PLEASE SET ONE OR MORE OF THE FOLLOWING VARIABLES TO TRUE: create_pr_dtag, create_latest_dtag, create_commit_hash_dtag, create_git_tag_dtag"
          exit 1