name: Reusable - Docker Build

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: gh-ubuntu-2404-x64
      config_creds:
        required: false
        type: boolean
        default: true
      artifact_name:
        required: false
        type: string
        default: ""
      aws_region:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      git_context:
        required: false
        type: string
        default: .
      docker_file_path:
        required: false
        type: string
        default: ./Dockerfile
      ecr_repository_name:
        required: true
        type: string
      default_branch:
        required: false
        type: string
        default: master
      create_pr_dtag:
        required: false
        type: boolean
        default: false
      create_latest_dtag:
        required: false
        type: boolean
        default: false
      create_commit_hash_dtag:
        required: false
        type: boolean
        default: false
      create_git_ref_dtag:
        required: false
        type: boolean
        default: false
      docker_args_list:
        required: false
        type: string
    secrets:
      aws_access_key:
        required: false
      aws_secret_key:
        required: false

jobs:
  docker-build:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        if: ${{ inputs.config_creds }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: "false"

      - name: Set ECR repository URL
        run: |
          echo "ECR_REPO=${{ steps.login-ecr.outputs.registry-url }}/${{ inputs.ecr_repository_name }}" >> $GITHUB_ENV

      - name: Download Artifacts
        if: ${{ inputs.artifact_name != '' }}
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.artifact_name }}

      - name: Create tag for PR
        if: ${{ inputs.create_pr_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create latest tag
        if: ${{ inputs.create_latest_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:latest" >> $GITHUB_ENV

      - name: Create commit hash tag
        if: ${{ inputs.create_commit_hash_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create docker tag for ${GITHUB_REF#refs/*/}
        if: ${{ inputs.create_git_ref_dtag }}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$ECR_REPO:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push
        if: ${{ env.DOCKER_TAG != '' }}
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ inputs.git_context }}"
          push: true
          tags: ${{ env.DOCKER_TAG }}
          provenance: false
          file: ${{ inputs.docker_file_path }}
          build-args: ${{ inputs.docker_args_list }}

      - name: Fail if no DOCKER_TAGS are specified
        if: ${{ env.DOCKER_TAG == '' }}
        run: |
          echo "NO DOCKER TAGS SPECIFIED. ACTION FAILED. PLEASE SET ONE OR MORE OF THE FOLLOWING VARIABLES TO TRUE: create_pr_dtag, create_latest_dtag, create_commit_hash_dtag, create_git_tag_dtag"
          exit 1
