name: Docker Build

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: ubuntu-20.04
      config_creds:
        required: false
        type: boolean
        default: true
      aws_region:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      git_context:
        required: false
        type: string
        default: .
      ecr_repository_name:
        required: true
        type: string
      default_branch:
        required: false
        type: string
        default: master
    secrets:
      aws_access_key:
        required: false
      aws_secret_key:
        required: false

jobs:
  docker-build:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        if: ${{ inputs.config_creds }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to the AWS registry
        run: |
          aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com

      - name: Create tag for PR
        if: ! contains(github.ref, inputs.default_branch)
        run: echo "DOCKER_TAG=${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create tag for merge
        if: contains(github.ref, inputs.default_branch)
        run: echo "DOCKER_TAG=${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:${GITHUB_SHA::7},${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:latest" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ inputs.git_context }}"
          push: true
          tags: ${{ env.DOCKER_TAG }}